### ISSUE TITLE
Ref<> does not work with string _ids

### ISSUE THREAD

**Issue by mfulop** [bangbang93/mongoose-typescript#2]
Hi,

How to use string _ids? Consider the following code snippet:

```
@model()
class A: extends Model<A> {
@id @prop() public readonly _id: string
}

@model()
class B: extends Model<B> {
@prop() @ref('A') public a: Ref<A>
}

const BModel: typeof B = getModel(B)
const b = new BModel()

b.a = 'someid' // Type 'string' is not assignable to type 'Ref<A>'

```

Seems like ```export declare type Ref<T> = Types.ObjectId | DocumentType<T>;``` limits the type to be ObjectId or the document itself but that is not always the case.

Thanks!

**Comment by bangbang93** [comment]
Maybe that should use `export type Ref<T extends any> = T['_id'] | DocumentType<T>`

**Comment by mfulop** [comment]
Thanks!

**Comment by mfulop** [comment]
Just a thought: unconventional, but the unique index field can be anything. Can we use the type of whichever field marked as @id?

**Comment by bangbang93** [comment]
Sorry, I can't understand. Would you like to make an example?

**Comment by mfulop** [comment]
Sorry, my bad. I remembered wrong, ref always used the field name “_id”. I think we can close this issue now. Thanks!
