### ISSUE TITLE
Motivation and comparison with existing module

### ISSUE THREAD

**Issue by dandv** [bangbang93/mongoose-typescript#4]
Hi @bangbang93, thanks for publishing this library. At the time it was published, there were already at least two packages with a similar goal:

* https://github.com/lstkz/ts-mongoose by @lstkz
* https://typegoose.github.io/typegoose/ by @hasezoey (fork of https://github.com/szokodiakos/typegoose)

I'm curious what the motivation was for creating `mongoose-typescript` and how it aims to differ from the existing projects. Thanks!

**Comment by bangbang93** [comment]
I had never found `ts-mongoose` before. But after reading the doc, it's not using decorators.
As for `typegoose`, here is my pull request szokodiakos/typegoose#194 which had not handled for a while. But I need this to be fixed. So I fork the repo in my company private npm registry firstly. And then I write this module.

**Comment by dandv** [comment]
> I had never found ts-mongoose before.

Well, when I'm trying to solve a problem, I search for existing solutions first. Helps me save a lot of effort. In this case, one can search for "typescript" at https://plugins.mongoosejs.io, and find several projects that attempt to do the same thing, combine TypeScript with mongoose.

> here is my pull request szokodiakos/typegoose#194 which had not handled for a while.

That repo is abandoned. Work has moved to https://github.com/typegoose/typegoose

**Comment by bangbang93** [comment]
I create that pr in 2018 when the repo had not to be abandoned.
In fact, I had learned a lot from typegoose.
