### ISSUE TITLE
Immutable 

### ISSUE THREAD

**Issue by akin2unde** [bangbang93/mongoose-typescript#6]
Please how can i do immutable on a property

**Comment by bangbang93** [comment]
Is this supported by mongoose?

**Comment by akin2unde** [comment]
Yes is supported. Sample const Model = mongoose.model('Test', new Schema({
  name: String,
  createdAt: {
    type: Date,
    immutable: true // Make `createdAt` immutable
  }
}, { timestamps: true }));
From this link http://thecodebarbarian.com/whats-new-in-mongoose-5-6-immutable-properties.html

**Comment by bangbang93** [comment]
```typescript
@prop() name: string
@prop({immutable: true}) createdAt: Date
```
Did you have tried this?

**Comment by akin2unde** [comment]
No , I will try it and get back to you

**Comment by akin2unde** [comment]
Thanks it worked
