### ISSUE TITLE
Are virtual fields supported ???

### ISSUE THREAD

**Issue by vjunjoced** [bangbang93/mongoose-typescript#8]
I am testing virtual fields but they don't seem to work.

I have the following definition of a model
https://gist.github.com/vjunjoced/269ba65d0ffdcf5c31cc3f6859795fb2

When the document is retrieved from the database and printed to the console the fields are not displayed

![image](https://user-images.githubusercontent.com/16103960/109673345-b4757d00-7b54-11eb-95d1-74c236a2bc2c.png)

My code that prints the document by console
```
async test(): Promise<Cat> {
    await this.catModel.newCat('Pepe 2');
    const pepe2 = await this.catModel.findOne({ _id: '603e48baf15939b50e29f4fc' }, { name: 1 });
    return pepe2;
  }
```

```
 constructor(private readonly emailService: EmailService) {
    this.emailService.test().then((value) => {
      console.log(value);
    });
  }
```

------
if i do it this way it works.
![image](https://user-images.githubusercontent.com/16103960/109674224-83497c80-7b55-11eb-90f7-80d622fba7a5.png)

![image](https://user-images.githubusercontent.com/16103960/109674018-54cba180-7b55-11eb-9a7f-2adbdf48b365.png)

Do you have any idea how I can do to avoid having to always call toObject passing `virtuals: true`? I understand that they are already defined in the model

**Comment by bangbang93** [comment]
Have you tried `console.log(value.toObject())`? And `value.testName2` should also works.
It seems you had set model level `toObject` and `toJSON` options with `@model`, it should work fine.
calling `console.log` to an object is actually not calling `toObject` or `toJSON`, instead of using `inspect` <https://nodejs.org/api/console.html#console_new_console_options>

**Comment by vjunjoced** [comment]
The problem was with the framework I was using.

Thanks!
